sudo: false
language: php
php:
- '7.1'
- '7.2'
- '7.3'
- '7.4snapshot'
- 'nightly'
matrix:
  fast_finish: true
  allow_failures:
  - php: '7.4snapshot'
  - php: 'nightly'
before_install:
- phpenv config-rm xdebug.ini || true
- "[[ $GITHUB_TOKEN ]] && composer config --global github-oauth.github.com $GITHUB_TOKEN"
install: composer install --no-interaction
script: make ci
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: RnRVCjftBvgJZxP/HDdZlUGgDwyZMOaGMeMM38TbYscoyN9zFB+80eBVLd4FMrutdLA3eC6RWQKVijGER6cB/hdZZwuxsj2xqDGSPwLqljmN/Qe+oIzXN78M/w6RThN+cmvYqL1W8Onrfv89YNV2YzJco/TISfIAIjUtkH1DPFsuZLhY31NXeM388nvBo4AcvD+dNluFMaRSBc+of6FysYf5fGct6X+TY6hFFuURv6R3irue1wvNA59mQqP1Te6nHXsLqGlqkUgaZ1Khqg/t6iQ1yJmm3jV43Sg7ttSDQHPe918geaK4wi3hoQyWnXRr9vB5hrHB9OaABUqEPrtE9e/UQWcXgdzqNPo7Ry5MpJTWfk6a0TsN+Rd8YB+zzW3LM+8cP7IXJjjTATkYsYKdXzlABq1XG+tLsBgQ556hmaG7eUYJG6a3GQcIlFJlQKSgFOGh+h6JOQOyv6HNwW/GlrBRfkCrVRxXFIXKFbdhbXds/hk0hOcJSlK6MwUatTDPZBj94KZFUl9KKFGzZGAF6eDhsfcAnNQitFgVvb5llrEUXPDMRFAUZDJwAFrSQybUyvL21P+/Z6yQABcaQzZZIxpsakWdTxGwjUoP5GTBAaXZo6dIjxWWpkXi/Yg/Lz0EGQiWwWPUhfXlk468qks9Eo/oBB9uMwcEkEbvhmzkHPE=
cache:
  directories:
  - "$HOME/.composer/cache/files"
